language: php

php:
  - 7.2.11

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

script:
  - ./run_tests
