language: php

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2.11
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2.11
      env: ILLUMINATE_VERSION=5.7.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require "illuminate/http:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/validation:${ILLUMINATE_VERSION}" --no-update

before_script:
  - composer update --prefer-source --no-interaction

script:
  - ./run_tests
