language: php

matrix:
  include:
    - php: 7.2.27
      env: ILLUMINATE_VERSION=6.11.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require "illuminate/http:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/validation:${ILLUMINATE_VERSION}" --no-update

before_script:
  - composer update --prefer-source --no-interaction

script:
  - ./run_tests
