language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require "illuminate/http:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/validation:${ILLUMINATE_VERSION}" --no-update

before_script:
  - composer update --prefer-source --no-interaction

script:
  - ./run_tests
