#!/bin/bash

# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

echo "################################################################################";
echo "# Functional Tests:"
echo "################################################################################";
./vendor/bin/phpunit --configuration phpunit.xml --colors --testsuite Functional
echo "################################################################################";
echo "";
